// Единый слой иконок (правило DS: иконки только отсюда, не из lucide напрямую).
// Размеры — только 16/20/24/32.
import {
  AlertTriangle,
  ArrowRight,
  Bell,
  BellOff,
  Bot,
  Building2,
  Camera,
  CameraOff,
  Car,
  Check,
  ChevronDown,
  ChevronRight,
  Cpu,
  Database,
  DoorOpen,
  Eye,
  EyeOff,
  FileDown,
  Folder,
  FolderPlus,
  ImagePlus,
  KeyRound,
  Languages,
  LayoutDashboard,
  LayoutGrid,
  LogOut,
  MapPin,
  Menu,
  MonitorPlay,
  Moon,
  Plus,
  Pencil,
  Search,
  Send,
  Settings,
  ShieldAlert,
  ShieldCheck,
  Sparkles,
  Sun,
  Swords,
  Timer,
  Trash2,
  TrendingUp,
  Undo2,
  User,
  UserCog,
  UserPlus,
  UserRound,
  UserRoundX,
  UserSearch,
  Users,
  Video,
  VideoOff,
  X,
  type LucideIcon,
} from '@/shared/ds/icons'
import type { EventType } from '@/shared/lib/format'

export {
  AlertTriangle,
  ArrowRight,
  Bell,
  BellOff,
  Bot,
  Building2,
  Camera,
  CameraOff,
  Car,
  Check,
  ChevronDown,
  ChevronRight,
  Cpu,
  Database,
  DoorOpen,
  Eye,
  EyeOff,
  FileDown,
  Folder,
  FolderPlus,
  ImagePlus,
  KeyRound,
  Languages,
  LayoutDashboard,
  LayoutGrid,
  LogOut,
  MapPin,
  Menu,
  MonitorPlay,
  Moon,
  Plus,
  Pencil,
  Search,
  Send,
  Settings,
  ShieldAlert,
  ShieldCheck,
  Sparkles,
  Sun,
  Swords,
  Timer,
  Trash2,
  TrendingUp,
  Undo2,
  User,
  UserCog,
  UserPlus,
  UserRound,
  UserRoundX,
  UserSearch,
  Users,
  Video,
  VideoOff,
  X,
}
export type { LucideIcon }

export const ICON_SIZE = { sm: 16, md: 20, lg: 24, xl: 32 } as const

export const eventIcon: Record<EventType, LucideIcon> = {
  zone_intrusion: ShieldAlert,
  loitering: Timer,
  after_hours_presence: Moon,
  person_entered: UserRound,
  person_exited: UserRoundX,
  camera_offline: CameraOff,
  camera_online: Camera,
  watchlist_match: UserSearch,
  person_recognized: UserRound,
  weapon_detected: Swords,
  vehicle_seen: Car,
  crowd_gathering: Users,
  queue_buildup: Timer,
  danger_zone_presence: ShieldAlert,
  hygiene_violation: ShieldAlert,
  fire_smoke: ShieldAlert,
  ppe_violation: ShieldAlert,
  package_damage: ShieldAlert,
  abandoned_object: ShieldAlert,
  equipment_idle: Car,
  illegal_parking: Car,
  loading_activity: Car,
  plate_recognized: Car,
  plate_unlisted: ShieldAlert,
}
