// Единый иконочный слой (lucide — тонкий-штриховой стиль, как Hugeicons в imaktab-front).
import {
  AlertTriangle,
  BarChart3,
  Check,
  Clock,
  Cpu,
  Database,
  DoorOpen,
  Film,
  LayoutDashboard,
  LogIn,
  LogOut,
  MapPin,
  Menu,
  Moon,
  MonitorPlay,
  Search,
  Settings,
  ShieldAlert,
  ShieldCheck,
  Timer,
  User,
  Users,
  Video,
  VideoOff,
  WifiOff,
  X,
  type LucideIcon,
} from 'lucide-react'
import type { EventType } from '@/shared/api/types'

export const eventIcon: Record<EventType, LucideIcon> = {
  zone_intrusion: ShieldAlert,
  loitering: Timer,
  after_hours_presence: Moon,
  person_entered: LogIn,
  person_exited: LogOut,
  camera_offline: VideoOff,
  camera_online: Video,
}

export {
  AlertTriangle,
  BarChart3,
  Check,
  Clock,
  Cpu,
  Database,
  DoorOpen,
  Film,
  LayoutDashboard,
  LogIn,
  LogOut,
  MapPin,
  Menu,
  MonitorPlay,
  Moon,
  Search,
  Settings,
  ShieldAlert,
  ShieldCheck,
  Timer,
  User,
  Users,
  Video,
  VideoOff,
  WifiOff,
  X,
}
export type { LucideIcon }
