// Единый слой иконок (правило DS: иконки только отсюда, не из lucide напрямую).
// Размеры — только 16/20/24/32.
import type { LucideIcon } from 'lucide-react'
import {
  AlertTriangle,
  Bell,
  BellOff,
  Bot,
  Camera,
  CameraOff,
  Car,
  Check,
  Cpu,
  Database,
  DoorOpen,
  FileDown,
  KeyRound,
  LayoutDashboard,
  LogOut,
  MapPin,
  MonitorPlay,
  Moon,
  Plus,
  Search,
  Send,
  Settings,
  ShieldAlert,
  ShieldCheck,
  Sparkles,
  Sun,
  Swords,
  Timer,
  Trash2,
  TrendingUp,
  UserCog,
  UserPlus,
  UserRound,
  UserRoundX,
  UserSearch,
  Users,
  Video,
  VideoOff,
  X,
} from 'lucide-react'
import type { EventType } from '@/shared/lib/format'

export {
  AlertTriangle,
  Bell,
  BellOff,
  Bot,
  Camera,
  CameraOff,
  Car,
  Check,
  Cpu,
  Database,
  DoorOpen,
  FileDown,
  KeyRound,
  LayoutDashboard,
  LogOut,
  MapPin,
  MonitorPlay,
  Moon,
  Plus,
  Search,
  Send,
  Settings,
  ShieldAlert,
  ShieldCheck,
  Sparkles,
  Sun,
  Swords,
  Timer,
  Trash2,
  TrendingUp,
  UserCog,
  UserPlus,
  UserRound,
  UserRoundX,
  UserSearch,
  Users,
  Video,
  VideoOff,
  X,
}
export type { LucideIcon }

export const ICON_SIZE = { sm: 16, md: 20, lg: 24, xl: 32 } as const

export const eventIcon: Record<EventType, LucideIcon> = {
  zone_intrusion: ShieldAlert,
  loitering: Timer,
  after_hours_presence: Moon,
  person_entered: UserRound,
  person_exited: UserRoundX,
  camera_offline: CameraOff,
  camera_online: Camera,
  watchlist_match: UserSearch,
  weapon_detected: Swords,
  vehicle_seen: Car,
}
